#if !canImport(ObjectiveC)
import XCTest

extension GausswiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GausswiftTests = [
        ("testBoxMullerPerformance", testBoxMullerPerformance),
        ("testBoxMullerPerformanceFast", testBoxMullerPerformanceFast),
        ("testDistribution_cgfloat_box_muller", testDistribution_cgfloat_box_muller),
        ("testDistribution_cgfloat_marsaglia", testDistribution_cgfloat_marsaglia),
        ("testDistribution_double_box_muller", testDistribution_double_box_muller),
        ("testDistribution_double_marsaglia", testDistribution_double_marsaglia),
        ("testDistribution_float_box_muller", testDistribution_float_box_muller),
        ("testDistribution_float_marsaglia", testDistribution_float_marsaglia),
        ("testMarsagliaPerformance", testMarsagliaPerformance),
        ("testMarsagliaPerformanceFast", testMarsagliaPerformanceFast),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GausswiftTests.__allTests__GausswiftTests),
    ]
}
#endif
